<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('SpLevel', 'doctrine');

/**
 * BaseSpLevel
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_level
 * @property string $role
 * @property Doctrine_Collection $SpUser
 * 
 * @method integer             getIdLevel()  Returns the current record's "id_level" value
 * @method string              getRole()     Returns the current record's "role" value
 * @method Doctrine_Collection getSpUser()   Returns the current record's "SpUser" collection
 * @method SpLevel             setIdLevel()  Sets the current record's "id_level" value
 * @method SpLevel             setRole()     Sets the current record's "role" value
 * @method SpLevel             setSpUser()   Sets the current record's "SpUser" collection
 * 
 * @package    sp_gallery
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSpLevel extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sp_level');
        $this->hasColumn('id_level', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'sp_level_id_level',
             'length' => 4,
             ));
        $this->hasColumn('role', 'string', null, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('SpUser', array(
             'local' => 'id_level',
             'foreign' => 'level_id'));
    }
}