<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('SpAlbum', 'doctrine');

/**
 * BaseSpAlbum
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_album
 * @property string $description
 * @property string $name
 * @property integer $user_id
 * @property integer $category_id
 * @property SpCategory $SpCategory
 * @property SpUser $SpUser
 * 
 * @method integer    getIdAlbum()     Returns the current record's "id_album" value
 * @method string     getDescription() Returns the current record's "description" value
 * @method string     getName()        Returns the current record's "name" value
 * @method integer    getUserId()      Returns the current record's "user_id" value
 * @method integer    getCategoryId()  Returns the current record's "category_id" value
 * @method SpCategory getSpCategory()  Returns the current record's "SpCategory" value
 * @method SpUser     getSpUser()      Returns the current record's "SpUser" value
 * @method SpAlbum    setIdAlbum()     Sets the current record's "id_album" value
 * @method SpAlbum    setDescription() Sets the current record's "description" value
 * @method SpAlbum    setName()        Sets the current record's "name" value
 * @method SpAlbum    setUserId()      Sets the current record's "user_id" value
 * @method SpAlbum    setCategoryId()  Sets the current record's "category_id" value
 * @method SpAlbum    setSpCategory()  Sets the current record's "SpCategory" value
 * @method SpAlbum    setSpUser()      Sets the current record's "SpUser" value
 * 
 * @package    sp_gallery
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSpAlbum extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sp_album');
        $this->hasColumn('id_album', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'sp_album_id_album',
             'length' => 4,
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('name', 'string', null, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('user_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('category_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('SpCategory', array(
             'local' => 'category_id',
             'foreign' => 'id_category'));

        $this->hasOne('SpUser', array(
             'local' => 'user_id',
             'foreign' => 'id_user'));
    }
}