<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('SfGalleryMembers', 'doctrine');

/**
 * BaseSfGalleryMembers
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_members
 * @property integer $gallery_id
 * @property integer $user_id
 * @property SfGuardUser $SfGuardUser
 * @property SfGallery $SfGallery
 * 
 * @method integer          getIdMembers()   Returns the current record's "id_members" value
 * @method integer          getGalleryId()   Returns the current record's "gallery_id" value
 * @method integer          getUserId()      Returns the current record's "user_id" value
 * @method SfGuardUser      getSfGuardUser() Returns the current record's "SfGuardUser" value
 * @method SfGallery        getSfGallery()   Returns the current record's "SfGallery" value
 * @method SfGalleryMembers setIdMembers()   Sets the current record's "id_members" value
 * @method SfGalleryMembers setGalleryId()   Sets the current record's "gallery_id" value
 * @method SfGalleryMembers setUserId()      Sets the current record's "user_id" value
 * @method SfGalleryMembers setSfGuardUser() Sets the current record's "SfGuardUser" value
 * @method SfGalleryMembers setSfGallery()   Sets the current record's "SfGallery" value
 * 
 * @package    sp_gallery
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSfGalleryMembers extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sf_gallery_members');
        $this->hasColumn('id_members', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'sf_gallery_members_id_members',
             'length' => 4,
             ));
        $this->hasColumn('gallery_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('user_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('SfGuardUser', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $this->hasOne('SfGallery', array(
             'local' => 'gallery_id',
             'foreign' => 'id_gallery'));
    }
}