<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('SfGallery', 'doctrine');

/**
 * BaseSfGallery
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_gallery
 * @property string $title
 * @property string $description
 * @property integer $user_id
 * @property date $created_at
 * @property date $updated_at
 * @property SfGuardUser $SfGuardUser
 * @property Doctrine_Collection $SfGalleryMembers
 * @property Doctrine_Collection $SfImages
 * 
 * @method integer             getIdGallery()        Returns the current record's "id_gallery" value
 * @method string              getTitle()            Returns the current record's "title" value
 * @method string              getDescription()      Returns the current record's "description" value
 * @method integer             getUserId()           Returns the current record's "user_id" value
 * @method date                getCreatedAt()        Returns the current record's "created_at" value
 * @method date                getUpdatedAt()        Returns the current record's "updated_at" value
 * @method SfGuardUser         getSfGuardUser()      Returns the current record's "SfGuardUser" value
 * @method Doctrine_Collection getSfGalleryMembers() Returns the current record's "SfGalleryMembers" collection
 * @method Doctrine_Collection getSfImages()         Returns the current record's "SfImages" collection
 * @method SfGallery           setIdGallery()        Sets the current record's "id_gallery" value
 * @method SfGallery           setTitle()            Sets the current record's "title" value
 * @method SfGallery           setDescription()      Sets the current record's "description" value
 * @method SfGallery           setUserId()           Sets the current record's "user_id" value
 * @method SfGallery           setCreatedAt()        Sets the current record's "created_at" value
 * @method SfGallery           setUpdatedAt()        Sets the current record's "updated_at" value
 * @method SfGallery           setSfGuardUser()      Sets the current record's "SfGuardUser" value
 * @method SfGallery           setSfGalleryMembers() Sets the current record's "SfGalleryMembers" collection
 * @method SfGallery           setSfImages()         Sets the current record's "SfImages" collection
 * 
 * @package    sp_gallery
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSfGallery extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sf_gallery');
        $this->hasColumn('id_gallery', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'sf_gallery_id_gallery',
             'length' => 4,
             ));
        $this->hasColumn('title', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('user_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('created_at', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('SfGuardUser', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $this->hasMany('SfGalleryMembers', array(
             'local' => 'id_gallery',
             'foreign' => 'gallery_id'));

        $this->hasMany('SfImages', array(
             'local' => 'id_gallery',
             'foreign' => 'gallery_id'));
    }
}