<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('SfImages', 'doctrine');

/**
 * BaseSfImages
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_image
 * @property integer $gallery_id
 * @property integer $user_id
 * @property string $description
 * @property string $order
 * @property string $name
 * @property date $created_at
 * @property date $updated_at
 * @property SfGallery $SfGallery
 * @property SfGuardUser $SfGuardUser
 * @property Doctrine_Collection $SfComments
 * 
 * @method integer             getIdImage()     Returns the current record's "id_image" value
 * @method integer             getGalleryId()   Returns the current record's "gallery_id" value
 * @method integer             getUserId()      Returns the current record's "user_id" value
 * @method string              getDescription() Returns the current record's "description" value
 * @method string              getOrder()       Returns the current record's "order" value
 * @method string              getName()        Returns the current record's "name" value
 * @method date                getCreatedAt()   Returns the current record's "created_at" value
 * @method date                getUpdatedAt()   Returns the current record's "updated_at" value
 * @method SfGallery           getSfGallery()   Returns the current record's "SfGallery" value
 * @method SfGuardUser         getSfGuardUser() Returns the current record's "SfGuardUser" value
 * @method Doctrine_Collection getSfComments()  Returns the current record's "SfComments" collection
 * @method SfImages            setIdImage()     Sets the current record's "id_image" value
 * @method SfImages            setGalleryId()   Sets the current record's "gallery_id" value
 * @method SfImages            setUserId()      Sets the current record's "user_id" value
 * @method SfImages            setDescription() Sets the current record's "description" value
 * @method SfImages            setOrder()       Sets the current record's "order" value
 * @method SfImages            setName()        Sets the current record's "name" value
 * @method SfImages            setCreatedAt()   Sets the current record's "created_at" value
 * @method SfImages            setUpdatedAt()   Sets the current record's "updated_at" value
 * @method SfImages            setSfGallery()   Sets the current record's "SfGallery" value
 * @method SfImages            setSfGuardUser() Sets the current record's "SfGuardUser" value
 * @method SfImages            setSfComments()  Sets the current record's "SfComments" collection
 * 
 * @package    sp_gallery
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSfImages extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sf_images');
        $this->hasColumn('id_image', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'sf_images_id_image',
             'length' => 4,
             ));
        $this->hasColumn('gallery_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('user_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('order', 'string', null, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('name', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('created_at', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('SfGallery', array(
             'local' => 'gallery_id',
             'foreign' => 'id_gallery'));

        $this->hasOne('SfGuardUser', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $this->hasMany('SfComments', array(
             'local' => 'id_image',
             'foreign' => 'image_id'));
    }
}