<?php

/**
 * SpUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sp_gallery
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class SpUser extends BaseSpUser
{
    /**
     *
     * @param Doctrine_Connection $con
     * @return <Doctrine_Connection> $con
     *
     */
    
    public function save(Doctrine_Connection $con = null)
	{
	  if ($this->getPassword())
	  {	    
	    $this->setPassword(sha1('$GallerySopia' . $this->getPassword()));
	    $this->setDate(date('Y-m-d'));
            sfContext::getInstance()->getLogger()->err('executeCreate-> '. $this->getdate());
	  }
	  return parent::save($con);
	}
}
