<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2010/11/03 14:09:45

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'pgsql:host=localhost;dbname=sgallery_git_beta',
  'username' => 'mic',
  'password' => 'simeadverti',
  'name' => 'doctrine',
)),);
