SfComments:
  connection: doctrine
  tableName: sf_comments
  columns:
    id_comments:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      sequence: sf_comments_id_comments
    image_id:
      type: integer(4)
      fixed: false
      unsigned: false
      notnull: true
      primary: false
    user:
      type: string()
      fixed: true
      unsigned: false
      notnull: true
      primary: false
    site:
      type: string()
      fixed: false
      unsigned: false
      notnull: false
      primary: false
    email:
      type: string()
      fixed: false
      unsigned: false
      notnull: true
      primary: false
    message:
      type: string()
      fixed: false
      unsigned: false
      notnull: true
      primary: false
    created_at:
      type: date(25)
      fixed: false
      unsigned: false
      notnull: false
      primary: false
    updated_at:
      type: date(25)
      fixed: false
      unsigned: false
      notnull: false
      primary: false
    ip:
      type: string()
      fixed: true
      unsigned: false
      notnull: true
      primary: false
    is_valid:
      type: boolean(1)
      fixed: false
      unsigned: false
      notnull: true
      default: 'false'
      primary: false
  relations:
    SfImages:
      local: image_id
      foreign: id_image
      type: one
SfGallery:
  connection: doctrine
  tableName: sf_gallery
  columns:
    id_gallery:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      sequence: sf_gallery_id_gallery
    title:
      type: string()
      fixed: false
      unsigned: false
      notnull: true
      primary: false
    description:
      type: string()
      fixed: false
      unsigned: false
      notnull: false
      primary: false
    user_id:
      type: integer(4)
      fixed: false
      unsigned: false
      notnull: true
      primary: false
    created_at:
      type: date(25)
      fixed: false
      unsigned: false
      notnull: false
      primary: false
    updated_at:
      type: date(25)
      fixed: false
      unsigned: false
      notnull: false
      primary: false
  relations:
    SfGuardUser:
      local: user_id
      foreign: id
      type: one
    SfGalleryMembers:
      local: id_gallery
      foreign: gallery_id
      type: many
    SfImages:
      local: id_gallery
      foreign: gallery_id
      type: many
SfGalleryMembers:
  connection: doctrine
  tableName: sf_gallery_members
  columns:
    id_members:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      sequence: sf_gallery_members_id_members
    gallery_id:
      type: integer(4)
      fixed: false
      unsigned: false
      notnull: true
      primary: false
    user_id:
      type: integer(4)
      fixed: false
      unsigned: false
      notnull: true
      primary: false
  relations:
    SfGuardUser:
      local: user_id
      foreign: id
      type: one
    SfGallery:
      local: gallery_id
      foreign: id_gallery
      type: one
SfGuardForgotPassword:
  connection: doctrine
  tableName: sf_guard_forgot_password
  columns:
    id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: true
      sequence: sf_guard_forgot_password_id
    user_id:
      type: integer(8)
      fixed: false
      unsigned: false
      notnull: true
      primary: false
    unique_key:
      type: string()
      fixed: false
      unsigned: false
      notnull: false
      primary: false
    expires_at:
      type: timestamp(25)
      fixed: false
      unsigned: false
      notnull: true
      primary: false
    created_at:
      type: timestamp(25)
      fixed: false
      unsigned: false
      notnull: true
      primary: false
    updated_at:
      type: timestamp(25)
      fixed: false
      unsigned: false
      notnull: true
      primary: false
  relations:
    SfGuardUser:
      local: user_id
      foreign: id
      type: one
SfGuardGroup:
  connection: doctrine
  tableName: sf_guard_group
  columns:
    id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: true
      sequence: sf_guard_group_id
    name:
      type: string()
      fixed: false
      unsigned: false
      notnull: false
      primary: false
    description:
      type: string()
      fixed: false
      unsigned: false
      notnull: false
      primary: false
    created_at:
      type: timestamp(25)
      fixed: false
      unsigned: false
      notnull: true
      primary: false
    updated_at:
      type: timestamp(25)
      fixed: false
      unsigned: false
      notnull: true
      primary: false
  relations:
    SfGuardGroupPermission:
      local: id
      foreign: group_id
      type: many
    SfGuardUserGroup:
      local: id
      foreign: group_id
      type: many
SfGuardGroupPermission:
  connection: doctrine
  tableName: sf_guard_group_permission
  columns:
    group_id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: true
    permission_id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: true
    created_at:
      type: timestamp(25)
      fixed: false
      unsigned: false
      notnull: true
      primary: false
    updated_at:
      type: timestamp(25)
      fixed: false
      unsigned: false
      notnull: true
      primary: false
  relations:
    SfGuardPermission:
      local: permission_id
      foreign: id
      type: one
    SfGuardGroup:
      local: group_id
      foreign: id
      type: one
SfGuardPermission:
  connection: doctrine
  tableName: sf_guard_permission
  columns:
    id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: true
      sequence: sf_guard_permission_id
    name:
      type: string()
      fixed: false
      unsigned: false
      notnull: false
      primary: false
    description:
      type: string()
      fixed: false
      unsigned: false
      notnull: false
      primary: false
    created_at:
      type: timestamp(25)
      fixed: false
      unsigned: false
      notnull: true
      primary: false
    updated_at:
      type: timestamp(25)
      fixed: false
      unsigned: false
      notnull: true
      primary: false
  relations:
    SfGuardGroupPermission:
      local: id
      foreign: permission_id
      type: many
    SfGuardUserPermission:
      local: id
      foreign: permission_id
      type: many
SfGuardRememberKey:
  connection: doctrine
  tableName: sf_guard_remember_key
  columns:
    id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: true
      sequence: sf_guard_remember_key_id
    user_id:
      type: integer(8)
      fixed: false
      unsigned: false
      notnull: false
      primary: false
    remember_key:
      type: string()
      fixed: false
      unsigned: false
      notnull: false
      primary: false
    ip_address:
      type: string()
      fixed: false
      unsigned: false
      notnull: false
      primary: false
    created_at:
      type: timestamp(25)
      fixed: false
      unsigned: false
      notnull: true
      primary: false
    updated_at:
      type: timestamp(25)
      fixed: false
      unsigned: false
      notnull: true
      primary: false
  relations:
    SfGuardUser:
      local: user_id
      foreign: id
      type: one
SfGuardUser:
  connection: doctrine
  tableName: sf_guard_user
  columns:
    id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: true
      sequence: sf_guard_user_id
    first_name:
      type: string()
      fixed: false
      unsigned: false
      notnull: false
      primary: false
    last_name:
      type: string()
      fixed: false
      unsigned: false
      notnull: false
      primary: false
    email_address:
      type: string()
      fixed: false
      unsigned: false
      notnull: true
      primary: false
    username:
      type: string()
      fixed: false
      unsigned: false
      notnull: true
      primary: false
    algorithm:
      type: string()
      fixed: false
      unsigned: false
      notnull: true
      default: sha1
      primary: false
    salt:
      type: string()
      fixed: false
      unsigned: false
      notnull: false
      primary: false
    password:
      type: string()
      fixed: false
      unsigned: false
      notnull: false
      primary: false
    is_active:
      type: boolean(1)
      fixed: false
      unsigned: false
      notnull: false
      default: 'true'
      primary: false
    is_super_admin:
      type: boolean(1)
      fixed: false
      unsigned: false
      notnull: false
      default: 'false'
      primary: false
    last_login:
      type: timestamp(25)
      fixed: false
      unsigned: false
      notnull: false
      primary: false
    created_at:
      type: timestamp(25)
      fixed: false
      unsigned: false
      notnull: true
      primary: false
    updated_at:
      type: timestamp(25)
      fixed: false
      unsigned: false
      notnull: true
      primary: false
  relations:
    SfGallery:
      local: id
      foreign: user_id
      type: many
    SfGalleryMembers:
      local: id
      foreign: user_id
      type: many
    SfGuardForgotPassword:
      local: id
      foreign: user_id
      type: many
    SfGuardRememberKey:
      local: id
      foreign: user_id
      type: many
    SfGuardUserGroup:
      local: id
      foreign: user_id
      type: many
    SfGuardUserPermission:
      local: id
      foreign: user_id
      type: many
    SfImages:
      local: id
      foreign: user_id
      type: many
SfGuardUserGroup:
  connection: doctrine
  tableName: sf_guard_user_group
  columns:
    user_id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: true
    group_id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: true
    created_at:
      type: timestamp(25)
      fixed: false
      unsigned: false
      notnull: true
      primary: false
    updated_at:
      type: timestamp(25)
      fixed: false
      unsigned: false
      notnull: true
      primary: false
  relations:
    SfGuardUser:
      local: user_id
      foreign: id
      type: one
    SfGuardGroup:
      local: group_id
      foreign: id
      type: one
SfGuardUserPermission:
  connection: doctrine
  tableName: sf_guard_user_permission
  columns:
    user_id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: true
    permission_id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: true
    created_at:
      type: timestamp(25)
      fixed: false
      unsigned: false
      notnull: true
      primary: false
    updated_at:
      type: timestamp(25)
      fixed: false
      unsigned: false
      notnull: true
      primary: false
  relations:
    SfGuardUser:
      local: user_id
      foreign: id
      type: one
    SfGuardPermission:
      local: permission_id
      foreign: id
      type: one
SfImages:
  connection: doctrine
  tableName: sf_images
  columns:
    id_image:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      sequence: sf_images_id_image
    gallery_id:
      type: integer(4)
      fixed: false
      unsigned: false
      notnull: true
      primary: false
    user_id:
      type: integer(4)
      fixed: false
      unsigned: false
      notnull: true
      primary: false
    description:
      type: string()
      fixed: false
      unsigned: false
      notnull: false
      primary: false
    order:
      type: string()
      fixed: true
      unsigned: false
      notnull: false
      primary: false
    name:
      type: string()
      fixed: false
      unsigned: false
      notnull: true
      primary: false
    created_at:
      type: date(25)
      fixed: false
      unsigned: false
      notnull: false
      primary: false
    updated_at:
      type: date(25)
      fixed: false
      unsigned: false
      notnull: false
      primary: false
  relations:
    SfGallery:
      local: gallery_id
      foreign: id_gallery
      type: one
    SfGuardUser:
      local: user_id
      foreign: id
      type: one
    SfComments:
      local: id_image
      foreign: image_id
      type: many
